### ISSUE TITLE
Not seen as a plugin on 1.16.4

### ISSUE THREAD

**Issue by DereC4** [GeorgH93/Minepacks#128] opened 2020-11-03 15:35 UTC
### Information
**Environment information**
*Plugin + server version info*:

```
Unknown command. Type "/help" for help. Last checked version was 2.3.19

```

*Online mode*: Yes

*BungeeCord*: No

**Server/crash log**

```

No crash log

```

**Plugin config (optional)**

```

Default config, unmodified besides drop on death 
```

### Details
**Description**  
Plugin won't work on latest version of minecraft, 1.16.4.
**Steps to reproduce**  
Run a server on 1.16.4

**Expected behavior**  
Minepacks to work or give some error message

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
This is probably just due to the new update, I'll patiently wait for the fix. Running /plugin command shows minepacks in red

**Comment by CrazyDuk** [comment] 2020-11-03 20:23
Yes my EssentialsX /help command doesn't detect the plugin at all and the commands don't work. I don't understand how it would stop working as it isn't a major update.

**Comment by GeorgH93** [comment] 2020-11-03 21:18
Duplicate of https://github.com/GeorgH93/Minepacks/issues/127

**Closed by GeorgH93** 2020-11-03 21:18 UTC
Labels: bug, duplicate
